server:
  port: 8092
  servlet:
    context-path: /property-view
spring:
  application:
    name: hotel
  liquibase:
    enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/hoteldb
    username: sa
    password: root
  h2:
    console:
      enabled: true
