server:
  port: 8092
  servlet:
    context-path: /property-view
spring:
  application:
    name: hotel
  liquibase:
    enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/hoteldb
    username: sa
    password: root
  h2:
    console:
      enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  info:
    title: Hotel API
    description: Documentation of Hotel API
    version: 1.0
    termsOfService: http://swagger.io/terms/
    contact:
      name: Dmitry Bulyha
      url: https://github.com/PeaChack
      email: dev.peachack@gmail.com
    license:
      name: Apache 2.0
      url: http://springdoc.org